services:
  database:
    image: postgres
    container_name: vaultfy_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pgbassola
      - POSTGRES_PASSWORD=WARdPBoC2621
      - POSTGRES_DB=vaultfy_postgres

  app:
    build: .
    container_name: vaultfy_app
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
      - /home/node/app/node_modules
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
